[build-system]
requires = ["setuptools>=65"]
build-backend = "setuptools.build_meta"

[project]
name = "guideosbookhub"
version = "0.1.0"
description = "Modern bookmark manager with cloud-agnostic synchronization via rclone"
authors = [
    {name = "Stephan R."}
]
license = {text = "GPL-3.0-or-later"}
requires-python = ">=3.10"

dependencies = [
    "PyQt6"
]

[project.scripts]
guideosbookhub = "guideosbookhub:main"